// This is an autogenerated file, DO NOT EDIT.
// This file was generated from `Gun.ts` by executing GenCast.
import type { IGun } from './Gun';

  export function CastToGun(obj: any): IGun | null {
    return (obj !== null && obj !== undefined && typeof(obj.caliber) === "number" && typeof(obj.manufacturer) === "string" && typeof(obj.ammoCapacity) === "number") ? obj : null;
  }
  