"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CastToPistol = CastToPistol;
// This is an autogenerated file, DO NOT EDIT.
// This file was generated from `Pistol.ts` by executing GenCast.
var Gun_gen_1 = require("./Gun.gen");
function CastToPistol(obj) {
    return (obj !== null && obj !== undefined && (0, Gun_gen_1.CastToGun)(obj) !== null && typeof (obj.hasManualSafety) === "boolean" && typeof (obj.gripType) === "string") ? obj : null;
}
