// This is an autogenerated file, DO NOT EDIT.
// This file was generated from `Pistol.ts` by executing GenCast.
import { CastToGun } from './Gun.gen';
import type { IPistol } from './Pistol';

  export function CastToPistol(obj: any): IPistol | null {
    return (obj !== null && obj !== undefined && CastToGun(obj) !== null && typeof(obj.hasManualSafety) === "boolean" && typeof(obj.gripType) === "string") ? obj : null;
  }
  