// This is an autogenerated file, DO NOT EDIT.
// This file was generated from `User.ts` by executing GenCast.
import type { IUser, IAdmin, IGuest } from './User';

  export function CastToUser(obj: any): IUser | null {
    return (obj !== null && obj !== undefined && typeof(obj.id) === "number" && typeof(obj.name) === "string" && typeof(obj.email) === "string" && typeof(obj.isActive) === "boolean") ? obj : null;
  }
  
  export function CastToAdmin(obj: any): IAdmin | null {
    return (obj !== null && obj !== undefined && typeof(obj.id) === "number" && typeof(obj.name) === "string" && typeof(obj.email) === "string" && typeof(obj.isActive) === "boolean" && obj.role === "admin") ? obj : null;
  }
  
  export function CastToGuest(obj: any): IGuest | null {
    return (obj !== null && obj !== undefined && typeof(obj.getDisplayName) === "function" && typeof(obj.sessionId) === "string") ? obj : null;
  }
  