/**
 * Integration tests for the generateCodegen() function.
 *
 * Each test creates a temporary directory, copies the relevant fixture source
 * files into it, runs the generator, and asserts on the output.  Using temp
 * dirs means the committed fixtures in tests/fixtures/ are never touched during
 * test runs.
 */
import { describe, it, expect } from 'vitest';
import fs from 'fs';
import path from 'path';
import os from 'os';

import { generateCodegen, GenCastConfig } from '../src/codegen';

const FIXTURES_DIR = path.resolve(__dirname, 'fixtures');

// ---------------------------------------------------------------------------
// Helper: spin up an isolated temp directory for one test scenario
// ---------------------------------------------------------------------------

function scratch(sourceFiles: string[], config: GenCastConfig = {}) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'gencast-test-'));

  for (const file of sourceFiles) {
    fs.copyFileSync(path.join(FIXTURES_DIR, file), path.join(dir, file));
  }

  const tsconfigPath = path.join(dir, 'tsconfig.json');
  fs.writeFileSync(
    tsconfigPath,
    JSON.stringify({
      compilerOptions: {
        target: 'ES2018',
        module: 'commonjs',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        moduleResolution: 'node',
      },
      include: ['*.ts'],
    })
  );

  const run = (overrides: GenCastConfig = {}) =>
    generateCodegen({ tsconfigPath, ...config, ...overrides });

  const read = (filename: string) =>
    fs.readFileSync(path.join(dir, filename), 'utf8');

  const exists = (filename: string) =>
    fs.existsSync(path.join(dir, filename));

  const cleanup = () =>
    fs.rmSync(dir, { recursive: true, force: true });

  return { dir, run, read, exists, cleanup };
}

// ---------------------------------------------------------------------------
// Basic interface generation
// ---------------------------------------------------------------------------

describe('generateCodegen - simple interface', () => {
  it('generates a cast function with the correct signature', () => {
    const { run, read, cleanup } = scratch(['Gun.ts']);
    try {
      run();
      const out = read('Gun.gen.ts');
      expect(out).toContain('export function CastToGun(obj: any): IGun | null');
    } finally {
      cleanup();
    }
  });

  it('emits the autogenerated header', () => {
    const { run, read, cleanup } = scratch(['Gun.ts']);
    try {
      run();
      const out = read('Gun.gen.ts');
      expect(out).toContain('// This is an autogenerated file, DO NOT EDIT.');
      expect(out).toContain("generated from `Gun.ts`");
    } finally {
      cleanup();
    }
  });

  it('imports the source type', () => {
    const { run, read, cleanup } = scratch(['Gun.ts']);
    try {
      run();
      expect(read('Gun.gen.ts')).toContain("import type { IGun } from './Gun'");
    } finally {
      cleanup();
    }
  });

  it('emits typeof checks for each interface property', () => {
    const { run, read, cleanup } = scratch(['Gun.ts']);
    try {
      run();
      const out = read('Gun.gen.ts');
      expect(out).toContain('typeof(obj.caliber) === "number"');
      expect(out).toContain('typeof(obj.manufacturer) === "string"');
      expect(out).toContain('typeof(obj.ammoCapacity) === "number"');
    } finally {
      cleanup();
    }
  });

  it('produces no gen file for a file with no exportable types', () => {
    // Write a source file with only a non-exported interface
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'gencast-test-'));
    try {
      fs.writeFileSync(path.join(dir, 'Empty.ts'), 'interface IPrivate { x: number; }');
      const tsconfigPath = path.join(dir, 'tsconfig.json');
      fs.writeFileSync(tsconfigPath, JSON.stringify({ compilerOptions: { strict: true }, include: ['*.ts'] }));
      generateCodegen({ tsconfigPath });
      expect(fs.existsSync(path.join(dir, 'Empty.gen.ts'))).toBe(false);
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });
});

// ---------------------------------------------------------------------------
// Interface inheritance
// ---------------------------------------------------------------------------

describe('generateCodegen - interface inheritance', () => {
  it('inlines all parent property checks when preferReuseCastFunctions is false', () => {
    const { run, read, cleanup } = scratch(['Gun.ts', 'Pistol.ts']);
    try {
      run({ preferReuseCastFunctions: false });
      const out = read('Pistol.gen.ts');
      // Must inline IGun's properties
      expect(out).toContain('typeof(obj.caliber) === "number"');
      expect(out).toContain('typeof(obj.manufacturer) === "string"');
      expect(out).toContain('typeof(obj.ammoCapacity) === "number"');
      // Must also check IPistol's own properties
      expect(out).toContain('typeof(obj.hasManualSafety) === "boolean"');
      expect(out).toContain('typeof(obj.gripType) === "string"');
      // Must NOT import from Gun.gen
      expect(out).not.toContain("from './Gun.gen'");
    } finally {
      cleanup();
    }
  });

  it('delegates to the parent cast function when preferReuseCastFunctions is true', () => {
    const { run, read, cleanup } = scratch(['Gun.ts', 'Pistol.ts']);
    try {
      run({ preferReuseCastFunctions: true });
      const out = read('Pistol.gen.ts');
      // Must call CastToGun rather than inlining
      expect(out).toContain('CastToGun(obj) !== null');
      // Must import that function from Gun.gen
      expect(out).toContain("from './Gun.gen'");
      // Must NOT inline IGun property checks
      expect(out).not.toContain('typeof(obj.caliber) === "number"');
    } finally {
      cleanup();
    }
  });

  it('generates same-file base function call for in-file inheritance', () => {
    const { run, read, cleanup } = scratch(['User.ts']);
    try {
      // IAdmin extends IUser — both in the same file
      run({ preferReuseCastFunctions: true });
      const out = read('User.gen.ts');
      expect(out).toContain('CastToUser(obj) !== null');
      // No self-import needed for same-file base
      expect(out).not.toContain("from './User.gen'");
    } finally {
      cleanup();
    }
  });
});

// ---------------------------------------------------------------------------
// Config: null check style
// ---------------------------------------------------------------------------

describe('generateCodegen - null check style', () => {
  it('emits obj != null (loose) by default', () => {
    const { run, read, cleanup } = scratch(['Gun.ts']);
    try {
      run({ strictNullCheck: false });
      const out = read('Gun.gen.ts');
      expect(out).toContain('obj != null');
      expect(out).not.toContain('obj !== null && obj !== undefined');
    } finally {
      cleanup();
    }
  });

  it('emits obj !== null && obj !== undefined when strictNullCheck is true', () => {
    const { run, read, cleanup } = scratch(['Gun.ts']);
    try {
      run({ strictNullCheck: true });
      expect(read('Gun.gen.ts')).toContain('obj !== null && obj !== undefined');
    } finally {
      cleanup();
    }
  });
});

// ---------------------------------------------------------------------------
// Config: failure return value
// ---------------------------------------------------------------------------

describe('generateCodegen - failureReturnValue', () => {
  it('uses null by default', () => {
    const { run, read, cleanup } = scratch(['Gun.ts']);
    try {
      run();
      const out = read('Gun.gen.ts');
      expect(out).toContain(': IGun | null');
      expect(out).toContain('? obj : null');
    } finally {
      cleanup();
    }
  });

  it('uses undefined when configured', () => {
    const { run, read, cleanup } = scratch(['Gun.ts']);
    try {
      run({ failureReturnValue: 'undefined' });
      const out = read('Gun.gen.ts');
      expect(out).toContain(': IGun | undefined');
      expect(out).toContain('? obj : undefined');
    } finally {
      cleanup();
    }
  });
});

// ---------------------------------------------------------------------------
// Config: removeIPrefix
// ---------------------------------------------------------------------------

describe('generateCodegen - removeIPrefix', () => {
  it('strips the I prefix from the function name by default', () => {
    const { run, read, cleanup } = scratch(['Gun.ts']);
    try {
      run();
      const out = read('Gun.gen.ts');
      expect(out).toContain('export function CastToGun');
      expect(out).not.toContain('export function CastToIGun');
    } finally {
      cleanup();
    }
  });

  it('keeps the I prefix when removeIPrefix is false', () => {
    const { run, read, cleanup } = scratch(['Gun.ts']);
    try {
      run({ removeIPrefix: false });
      expect(read('Gun.gen.ts')).toContain('export function CastToIGun');
    } finally {
      cleanup();
    }
  });
});

// ---------------------------------------------------------------------------
// Config: custom function prefix
// ---------------------------------------------------------------------------

describe('generateCodegen - funcPrefix', () => {
  it('applies a custom prefix to generated functions', () => {
    const { run, read, cleanup } = scratch(['Gun.ts']);
    try {
      run({ funcPrefix: 'assertIs' });
      expect(read('Gun.gen.ts')).toContain('export function assertIsGun');
    } finally {
      cleanup();
    }
  });
});

// ---------------------------------------------------------------------------
// Config: JavaScript output
// ---------------------------------------------------------------------------

describe('generateCodegen - outputLanguage: js', () => {
  it('writes a .gen.js file instead of .gen.ts', () => {
    const { run, exists, cleanup } = scratch(['Gun.ts']);
    try {
      run({ outputLanguage: 'js' });
      expect(exists('Gun.gen.js')).toBe(true);
      expect(exists('Gun.gen.ts')).toBe(false);
    } finally {
      cleanup();
    }
  });

  it('omits type annotations and import type statements', () => {
    const { run, dir, cleanup } = scratch(['Gun.ts']);
    try {
      run({ outputLanguage: 'js' });
      const out = fs.readFileSync(path.join(dir, 'Gun.gen.js'), 'utf8');
      expect(out).toContain('export function CastToGun(obj)');
      expect(out).not.toContain(': IGun |');
      expect(out).not.toContain('import type');
    } finally {
      cleanup();
    }
  });
});

// ---------------------------------------------------------------------------
// Config: type alias generation
// ---------------------------------------------------------------------------

describe('generateCodegen - type aliases (generateTypeCasts: true)', () => {
  it('generates casts for primitive type aliases', () => {
    const { run, read, cleanup } = scratch(['Types.ts']);
    try {
      run({ generateTypeCasts: true });
      const out = read('Types.gen.ts');
      expect(out).toContain('export function CastToID');
      expect(out).toContain('typeof(obj) === "number"');
      expect(out).toContain('export function CastToUsername');
      expect(out).toContain('typeof(obj) === "string"');
      expect(out).toContain('export function CastToIsActive');
      expect(out).toContain('typeof(obj) === "boolean"');
    } finally {
      cleanup();
    }
  });

  it('generates equality checks for string literal union types', () => {
    const { run, read, cleanup } = scratch(['Types.ts']);
    try {
      run({ generateTypeCasts: true });
      const out = read('Types.gen.ts');
      expect(out).toContain('export function CastToStatus');
      expect(out).toContain('obj === "active"');
      expect(out).toContain('obj === "inactive"');
      expect(out).toContain('obj === "pending"');
    } finally {
      cleanup();
    }
  });

  it('generates property checks for object type aliases', () => {
    const { run, read, cleanup } = scratch(['Types.ts']);
    try {
      run({ generateTypeCasts: true });
      const out = read('Types.gen.ts');
      expect(out).toContain('export function CastToPoint');
      expect(out).toContain('typeof(obj.x) === "number"');
      expect(out).toContain('typeof(obj.y) === "number"');
    } finally {
      cleanup();
    }
  });

  it('does not generate a file for a types-only file when generateTypeCasts is false', () => {
    const { run, exists, cleanup } = scratch(['Types.ts']);
    try {
      run({ generateTypeCasts: false });
      // Types.ts has no interfaces, only type aliases — nothing to generate
      expect(exists('Types.gen.ts')).toBe(false);
    } finally {
      cleanup();
    }
  });
});

// ---------------------------------------------------------------------------
// Config: class cast generation
// ---------------------------------------------------------------------------

describe('generateCodegen - class casts (generateClassCasts: true)', () => {
  it('generates an instanceof check for exported classes', () => {
    const { run, read, cleanup } = scratch(['User.ts']);
    try {
      run({ generateClassCasts: true });
      const out = read('User.gen.ts');
      expect(out).toContain('export function CastToUserAccount');
      expect(out).toContain('obj instanceof UserAccount');
    } finally {
      cleanup();
    }
  });
});

// ---------------------------------------------------------------------------
// Skipping already-generated files
// ---------------------------------------------------------------------------

describe('generateCodegen - skips .gen.ts inputs', () => {
  it('does not process an existing .gen.ts file as a new source', () => {
    const { run, exists, cleanup } = scratch(['Gun.ts', 'Gun.gen.ts']);
    try {
      run();
      // The generator should not produce a doubly-generated file
      expect(exists('Gun.gen.gen.ts')).toBe(false);
    } finally {
      cleanup();
    }
  });
});
