/**
 * Integration tests for the generateCodegen() function.
 *
 * Each test creates a temporary directory, copies the relevant fixture source
 * files into it, runs the generator, and asserts on the output.  Using temp
 * dirs means the committed fixtures in tests/fixtures/ are never touched during
 * test runs.
 */
import { describe, it, expect } from 'vitest';
import fs from 'fs';
import path from 'path';
import os from 'os';

import { generateCodegen, generateCodegenForPath, generateUtilityCastsFile, GenCastConfig } from '../src/codegen';

const FIXTURES_DIR = path.resolve(__dirname, 'fixtures');

// ---------------------------------------------------------------------------
// Helper: spin up an isolated temp directory for one test scenario
// ---------------------------------------------------------------------------

function scratch(sourceFiles: string[], config: GenCastConfig = {}) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'gencast-test-'));

  for (const file of sourceFiles) {
    fs.copyFileSync(path.join(FIXTURES_DIR, file), path.join(dir, file));
  }

  const tsconfigPath = path.join(dir, 'tsconfig.json');
  fs.writeFileSync(
    tsconfigPath,
    JSON.stringify({
      compilerOptions: {
        target: 'ES2018',
        module: 'commonjs',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        moduleResolution: 'node',
      },
      include: ['*.ts'],
    })
  );

  const run = (overrides: GenCastConfig = {}) =>
    generateCodegen({ tsconfigPath, ...config, ...overrides });

  const read = (filename: string) =>
    fs.readFileSync(path.join(dir, filename), 'utf8');

  const exists = (filename: string) =>
    fs.existsSync(path.join(dir, filename));

  const cleanup = () =>
    fs.rmSync(dir, { recursive: true, force: true });

  return { dir, run, read, exists, cleanup };
}

// ---------------------------------------------------------------------------
// Basic interface generation
// ---------------------------------------------------------------------------

describe('generateCodegen - simple interface', () => {
  it('generates a cast function with the correct signature', () => {
    const { run, read, cleanup } = scratch(['Gun.ts']);
    try {
      run();
      const out = read('Gun.gen.ts');
      expect(out).toContain('export function CastToGun(obj: any): IGun | null');
    } finally {
      cleanup();
    }
  });

  it('emits the autogenerated header', () => {
    const { run, read, cleanup } = scratch(['Gun.ts']);
    try {
      run();
      const out = read('Gun.gen.ts');
      expect(out).toContain('// This is an autogenerated file, DO NOT EDIT.');
      expect(out).toContain("generated from `Gun.ts`");
    } finally {
      cleanup();
    }
  });

  it('imports the source type', () => {
    const { run, read, cleanup } = scratch(['Gun.ts']);
    try {
      run();
      expect(read('Gun.gen.ts')).toContain("import type { IGun } from './Gun'");
    } finally {
      cleanup();
    }
  });

  it('emits typeof checks for each interface property', () => {
    const { run, read, cleanup } = scratch(['Gun.ts']);
    try {
      run();
      const out = read('Gun.gen.ts');
      expect(out).toContain('typeof(obj.caliber) === "number"');
      expect(out).toContain('typeof(obj.manufacturer) === "string"');
      expect(out).toContain('typeof(obj.ammoCapacity) === "number"');
    } finally {
      cleanup();
    }
  });

  it('produces no gen file for a file with no exportable types', () => {
    // Write a source file with only a non-exported interface
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'gencast-test-'));
    try {
      fs.writeFileSync(path.join(dir, 'Empty.ts'), 'interface IPrivate { x: number; }');
      const tsconfigPath = path.join(dir, 'tsconfig.json');
      fs.writeFileSync(tsconfigPath, JSON.stringify({ compilerOptions: { strict: true }, include: ['*.ts'] }));
      generateCodegen({ tsconfigPath });
      expect(fs.existsSync(path.join(dir, 'Empty.gen.ts'))).toBe(false);
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });
});

// ---------------------------------------------------------------------------
// Interface inheritance
// ---------------------------------------------------------------------------

describe('generateCodegen - interface inheritance', () => {
  it('inlines all parent property checks when preferReuseCastFunctions is false', () => {
    const { run, read, cleanup } = scratch(['Gun.ts', 'Pistol.ts']);
    try {
      run({ preferReuseCastFunctions: false });
      const out = read('Pistol.gen.ts');
      // Must inline IGun's properties
      expect(out).toContain('typeof(obj.caliber) === "number"');
      expect(out).toContain('typeof(obj.manufacturer) === "string"');
      expect(out).toContain('typeof(obj.ammoCapacity) === "number"');
      // Must also check IPistol's own properties
      expect(out).toContain('typeof(obj.hasManualSafety) === "boolean"');
      expect(out).toContain('typeof(obj.gripType) === "string"');
      // Must NOT import from Gun.gen
      expect(out).not.toContain("from './Gun.gen'");
    } finally {
      cleanup();
    }
  });

  it('delegates to the parent cast function when preferReuseCastFunctions is true', () => {
    const { run, read, cleanup } = scratch(['Gun.ts', 'Pistol.ts']);
    try {
      run({ preferReuseCastFunctions: true });
      const out = read('Pistol.gen.ts');
      // Must call CastToGun rather than inlining
      expect(out).toContain('CastToGun(obj) !== null');
      // Must import that function from Gun.gen
      expect(out).toContain("from './Gun.gen'");
      // Must NOT inline IGun property checks
      expect(out).not.toContain('typeof(obj.caliber) === "number"');
    } finally {
      cleanup();
    }
  });

  it('generates same-file base function call for in-file inheritance', () => {
    const { run, read, cleanup } = scratch(['User.ts']);
    try {
      // IAdmin extends IUser — both in the same file
      run({ preferReuseCastFunctions: true });
      const out = read('User.gen.ts');
      expect(out).toContain('CastToUser(obj) !== null');
      // No self-import needed for same-file base
      expect(out).not.toContain("from './User.gen'");
    } finally {
      cleanup();
    }
  });
});

// ---------------------------------------------------------------------------
// Config: null check style
// ---------------------------------------------------------------------------

describe('generateCodegen - null check style', () => {
  it('emits obj != null (loose) by default', () => {
    const { run, read, cleanup } = scratch(['Gun.ts']);
    try {
      run({ strictNullCheck: false });
      const out = read('Gun.gen.ts');
      expect(out).toContain('obj != null');
      expect(out).not.toContain('obj !== null && obj !== undefined');
    } finally {
      cleanup();
    }
  });

  it('emits obj !== null && obj !== undefined when strictNullCheck is true', () => {
    const { run, read, cleanup } = scratch(['Gun.ts']);
    try {
      run({ strictNullCheck: true });
      expect(read('Gun.gen.ts')).toContain('obj !== null && obj !== undefined');
    } finally {
      cleanup();
    }
  });
});

// ---------------------------------------------------------------------------
// Config: failure return value
// ---------------------------------------------------------------------------

describe('generateCodegen - failureReturnValue', () => {
  it('uses null by default', () => {
    const { run, read, cleanup } = scratch(['Gun.ts']);
    try {
      run();
      const out = read('Gun.gen.ts');
      expect(out).toContain(': IGun | null');
      expect(out).toContain('? obj : null');
    } finally {
      cleanup();
    }
  });

  it('uses undefined when configured', () => {
    const { run, read, cleanup } = scratch(['Gun.ts']);
    try {
      run({ failureReturnValue: 'undefined' });
      const out = read('Gun.gen.ts');
      expect(out).toContain(': IGun | undefined');
      expect(out).toContain('? obj : undefined');
    } finally {
      cleanup();
    }
  });
});

// ---------------------------------------------------------------------------
// Config: removeIPrefix
// ---------------------------------------------------------------------------

describe('generateCodegen - removeIPrefix', () => {
  it('strips the I prefix from the function name by default', () => {
    const { run, read, cleanup } = scratch(['Gun.ts']);
    try {
      run();
      const out = read('Gun.gen.ts');
      expect(out).toContain('export function CastToGun');
      expect(out).not.toContain('export function CastToIGun');
    } finally {
      cleanup();
    }
  });

  it('keeps the I prefix when removeIPrefix is false', () => {
    const { run, read, cleanup } = scratch(['Gun.ts']);
    try {
      run({ removeIPrefix: false });
      expect(read('Gun.gen.ts')).toContain('export function CastToIGun');
    } finally {
      cleanup();
    }
  });
});

// ---------------------------------------------------------------------------
// Config: custom function prefix
// ---------------------------------------------------------------------------

describe('generateCodegen - funcPrefix', () => {
  it('applies a custom prefix to generated functions', () => {
    const { run, read, cleanup } = scratch(['Gun.ts']);
    try {
      run({ funcPrefix: 'assertIs' });
      expect(read('Gun.gen.ts')).toContain('export function assertIsGun');
    } finally {
      cleanup();
    }
  });
});

// ---------------------------------------------------------------------------
// Config: JavaScript output
// ---------------------------------------------------------------------------

describe('generateCodegen - outputLanguage: js', () => {
  it('writes a .gen.js file instead of .gen.ts', () => {
    const { run, exists, cleanup } = scratch(['Gun.ts']);
    try {
      run({ outputLanguage: 'js' });
      expect(exists('Gun.gen.js')).toBe(true);
      expect(exists('Gun.gen.ts')).toBe(false);
    } finally {
      cleanup();
    }
  });

  it('omits type annotations and import type statements', () => {
    const { run, dir, cleanup } = scratch(['Gun.ts']);
    try {
      run({ outputLanguage: 'js' });
      const out = fs.readFileSync(path.join(dir, 'Gun.gen.js'), 'utf8');
      expect(out).toContain('export function CastToGun(obj)');
      expect(out).not.toContain(': IGun |');
      expect(out).not.toContain('import type');
    } finally {
      cleanup();
    }
  });
});

// ---------------------------------------------------------------------------
// Config: type alias generation
// ---------------------------------------------------------------------------

describe('generateCodegen - type aliases (generateTypeCasts: true)', () => {
  it('generates casts for primitive type aliases', () => {
    const { run, read, cleanup } = scratch(['Types.ts']);
    try {
      run({ generateTypeCasts: true });
      const out = read('Types.gen.ts');
      expect(out).toContain('export function CastToID');
      expect(out).toContain('typeof(obj) === "number"');
      expect(out).toContain('export function CastToUsername');
      expect(out).toContain('typeof(obj) === "string"');
      expect(out).toContain('export function CastToIsActive');
      expect(out).toContain('typeof(obj) === "boolean"');
    } finally {
      cleanup();
    }
  });

  it('generates equality checks for string literal union types', () => {
    const { run, read, cleanup } = scratch(['Types.ts']);
    try {
      run({ generateTypeCasts: true });
      const out = read('Types.gen.ts');
      expect(out).toContain('export function CastToStatus');
      expect(out).toContain('obj === "active"');
      expect(out).toContain('obj === "inactive"');
      expect(out).toContain('obj === "pending"');
    } finally {
      cleanup();
    }
  });

  it('generates property checks for object type aliases', () => {
    const { run, read, cleanup } = scratch(['Types.ts']);
    try {
      run({ generateTypeCasts: true });
      const out = read('Types.gen.ts');
      expect(out).toContain('export function CastToPoint');
      expect(out).toContain('typeof(obj.x) === "number"');
      expect(out).toContain('typeof(obj.y) === "number"');
    } finally {
      cleanup();
    }
  });

  it('does not generate a file for a types-only file when generateTypeCasts is false', () => {
    const { run, exists, cleanup } = scratch(['Types.ts']);
    try {
      run({ generateTypeCasts: false });
      // Types.ts has no interfaces, only type aliases — nothing to generate
      expect(exists('Types.gen.ts')).toBe(false);
    } finally {
      cleanup();
    }
  });
});

// ---------------------------------------------------------------------------
// Regression: enum unions must not emit inline `import(...)` expressions
// ---------------------------------------------------------------------------

describe('generateCodegen - enum unions', () => {
  // Enum members are literal types in TypeScript, but ts-morph's `Type.getText()`
  // renders cross-file enum members as `import("/abs/path").Enum.Member`. Without
  // an explicit fix, that text leaks into the generated cast as an inline
  // `import(...)` expression — both broken at runtime and a bundler nightmare.
  it('emits literal-value equality checks for a union of string-valued enums', () => {
    const { run, read, cleanup } = scratch(['EnumUnion.ts']);
    try {
      run({ generateTypeCasts: true });
      const out = read('EnumUnion.gen.ts');
      expect(out).not.toMatch(/import\s*\(/);
      expect(out).toContain('export function CastToAnyAnimal');
      expect(out).toContain('obj === "cat"');
      expect(out).toContain('obj === "dog"');
      expect(out).toContain('obj === "bird"');
      expect(out).toContain('obj === "fish"');
    } finally {
      cleanup();
    }
  });

  it('emits literal-value equality checks for a numeric enum alias', () => {
    const { run, read, cleanup } = scratch(['EnumUnion.ts']);
    try {
      run({ generateTypeCasts: true });
      const out = read('EnumUnion.gen.ts');
      expect(out).not.toMatch(/import\s*\(/);
      expect(out).toContain('export function CastToAnyNumbered');
      expect(out).toContain('obj === 0');
      expect(out).toContain('obj === 1');
      expect(out).toContain('obj === 2');
    } finally {
      cleanup();
    }
  });

  it('emits literal checks for enum-typed interface properties', () => {
    const { run, read, cleanup } = scratch(['EnumUnion.ts']);
    try {
      run({ generateTypeCasts: true });
      const out = read('EnumUnion.gen.ts');
      expect(out).not.toMatch(/import\s*\(/);
      expect(out).toContain('export function CastToHasEnumProp');
      expect(out).toContain('obj.pet === "cat"');
      expect(out).toContain('obj.rank === 0');
      expect(out).toContain('obj.multi === "bird"');
    } finally {
      cleanup();
    }
  });
});

// ---------------------------------------------------------------------------
// Config: class cast generation
// ---------------------------------------------------------------------------

describe('generateCodegen - class casts (generateClassCasts: true)', () => {
  it('generates an instanceof check for exported classes', () => {
    const { run, read, cleanup } = scratch(['User.ts']);
    try {
      run({ generateClassCasts: true });
      const out = read('User.gen.ts');
      expect(out).toContain('export function CastToUserAccount');
      expect(out).toContain('obj instanceof UserAccount');
    } finally {
      cleanup();
    }
  });
});

// ---------------------------------------------------------------------------
// Skipping already-generated files
// ---------------------------------------------------------------------------

describe('generateCodegen - skips .gen.ts inputs', () => {
  it('does not process an existing .gen.ts file as a new source', () => {
    const { run, exists, cleanup } = scratch(['Gun.ts', 'Gun.gen.ts']);
    try {
      run();
      // The generator should not produce a doubly-generated file
      expect(exists('Gun.gen.gen.ts')).toBe(false);
    } finally {
      cleanup();
    }
  });
});

// ---------------------------------------------------------------------------
// Constructor / construct-signature types
// ---------------------------------------------------------------------------

describe('generateCodegen - constructor types', () => {
  it('emits a prototype-in check for an interface property typed as a constructor', () => {
    const { run, read, cleanup } = scratch(['ConstructorTypes.ts']);
    try {
      run();
      const out = read('ConstructorTypes.gen.ts');
      // Must use the stricter constructable check, NOT a bare typeof
      expect(out).toContain(`typeof(obj.ctor) === "function" && 'prototype' in obj.ctor`);
      // The interface property check must be inline, not a delegated call to the cast function
      expect(out).not.toContain('CastToComponentConstructor(obj.ctor)');
    } finally {
      cleanup();
    }
  });

  it('emits a prototype-in check for an inline construct signature property', () => {
    const { run, read, cleanup } = scratch(['ConstructorTypes.ts']);
    try {
      run();
      const out = read('ConstructorTypes.gen.ts');
      expect(out).toContain(`typeof(obj.create) === "function" && 'prototype' in obj.create`);
    } finally {
      cleanup();
    }
  });

  it('does not generate a cast function for a stand-alone constructor type alias by default', () => {
    const { run, read, cleanup } = scratch(['ConstructorTypes.ts']);
    try {
      run({ generateTypeCasts: false });
      const out = read('ConstructorTypes.gen.ts');
      // generateTypeCasts is off, so no standalone cast for the type alias
      expect(out).not.toContain('CastToComponentConstructor');
    } finally {
      cleanup();
    }
  });

  it('generates a typeof+prototype-in cast function for a constructor type alias when generateTypeCasts is true', () => {
    const { run, read, cleanup } = scratch(['ConstructorTypes.ts']);
    try {
      run({ generateTypeCasts: true });
      const out = read('ConstructorTypes.gen.ts');
      expect(out).toContain('export function CastToComponentConstructor');
      expect(out).toContain(`typeof(obj) === "function" && 'prototype' in obj`);
    } finally {
      cleanup();
    }
  });

  it('still emits a plain typeof check for regular interface methods (not constructors)', () => {
    const { run, read, cleanup } = scratch(['ConstructorTypes.ts']);
    try {
      run();
      const out = read('ConstructorTypes.gen.ts');
      // IService.getDisplayName is a call signature, not a construct signature —
      // it should use the plain typeof check without the prototype guard
      expect(out).toContain(`typeof(obj.getDisplayName) === "function"`);
      expect(out).not.toContain(`'prototype' in obj.getDisplayName`);
    } finally {
      cleanup();
    }
  });
});

// ---------------------------------------------------------------------------
// generateUtilityCastsFile - CastToArray parameter order
// ---------------------------------------------------------------------------

describe('generateUtilityCastsFile - CastToArray', () => {
  function scratchUtils(config: GenCastConfig = {}) {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'gencast-utils-test-'));
    const outputPath = path.join(dir, 'gencast.gen.ts');
    const cleanup = () => fs.rmSync(dir, { recursive: true, force: true });
    const read = () => fs.readFileSync(outputPath, 'utf8');
    const run = (overrides: GenCastConfig = {}) =>
      generateUtilityCastsFile(outputPath, { ...config, ...overrides });
    return { run, read, cleanup };
  }

  it('emits CastToArray with arr as the first parameter', () => {
    const { run, read, cleanup } = scratchUtils();
    try {
      run();
      expect(read()).toContain('CastToArray<T>(arr: any, castFn:');
    } finally {
      cleanup();
    }
  });

  it('emits CastToArray with arr as the first parameter in JS output', () => {
    const { run, read, cleanup } = scratchUtils({ outputLanguage: 'js' });
    try {
      run();
      expect(read()).toContain('CastToArray(arr, castFn)');
    } finally {
      cleanup();
    }
  });

  it('documents the correct parameter order in the usage comment', () => {
    const { run, read, cleanup } = scratchUtils();
    try {
      run();
      expect(read()).toContain('CastToArray(myArray, CastToThing)');
    } finally {
      cleanup();
    }
  });
});

// ---------------------------------------------------------------------------
// generateCodegenForPath - single file / directory targeting
// ---------------------------------------------------------------------------

describe('generateCodegenForPath - single file', () => {
  it('generates a cast file only for the targeted file', () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'gencast-test-'));
    try {
      fs.copyFileSync(path.join(FIXTURES_DIR, 'Gun.ts'), path.join(dir, 'Gun.ts'));
      fs.copyFileSync(path.join(FIXTURES_DIR, 'Types.ts'), path.join(dir, 'Types.ts'));
      const tsconfigPath = path.join(dir, 'tsconfig.json');
      fs.writeFileSync(
        tsconfigPath,
        JSON.stringify({ compilerOptions: { strict: true }, include: ['*.ts'] })
      );

      generateCodegenForPath(path.join(dir, 'Gun.ts'), { tsconfigPath });

      expect(fs.existsSync(path.join(dir, 'Gun.gen.ts'))).toBe(true);
      // Types.ts was NOT targeted — its gen file must not be created
      expect(fs.existsSync(path.join(dir, 'Types.gen.ts'))).toBe(false);
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  it('generates correct content for the targeted file', () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'gencast-test-'));
    try {
      fs.copyFileSync(path.join(FIXTURES_DIR, 'Gun.ts'), path.join(dir, 'Gun.ts'));
      const tsconfigPath = path.join(dir, 'tsconfig.json');
      fs.writeFileSync(
        tsconfigPath,
        JSON.stringify({ compilerOptions: { strict: true }, include: ['*.ts'] })
      );

      generateCodegenForPath(path.join(dir, 'Gun.ts'), { tsconfigPath });

      const out = fs.readFileSync(path.join(dir, 'Gun.gen.ts'), 'utf8');
      expect(out).toContain('export function CastToGun(obj: any): IGun | null');
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe('generateCodegenForPath - directory', () => {
  it('generates cast files for all source files in the target directory', () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'gencast-test-'));
    const subdir = path.join(root, 'models');
    fs.mkdirSync(subdir);
    try {
      fs.copyFileSync(path.join(FIXTURES_DIR, 'Gun.ts'), path.join(subdir, 'Gun.ts'));
      fs.copyFileSync(path.join(FIXTURES_DIR, 'Types.ts'), path.join(subdir, 'Types.ts'));
      // A file outside the target directory
      fs.copyFileSync(path.join(FIXTURES_DIR, 'User.ts'), path.join(root, 'User.ts'));
      const tsconfigPath = path.join(root, 'tsconfig.json');
      fs.writeFileSync(
        tsconfigPath,
        JSON.stringify({ compilerOptions: { strict: true }, include: ['**/*.ts'] })
      );

      generateCodegenForPath(subdir, { tsconfigPath });

      // Both files inside the directory are processed
      expect(fs.existsSync(path.join(subdir, 'Gun.gen.ts'))).toBe(true);
      expect(fs.existsSync(path.join(subdir, 'Types.gen.ts'))).toBe(true);
      // The file outside the directory is NOT processed
      expect(fs.existsSync(path.join(root, 'User.gen.ts'))).toBe(false);
    } finally {
      fs.rmSync(root, { recursive: true, force: true });
    }
  });
});

// ---------------------------------------------------------------------------
// Record<K, V> handling and node_modules-declared types
// ---------------------------------------------------------------------------

describe('generateCodegen - Record<K, V> properties', () => {
  it('emits an inline structural check rather than referencing CastToRecord', () => {
    const { run, read, cleanup } = scratch(['RecordCase.ts']);
    try {
      run();
      const out = read('RecordCase.gen.ts');
      // Must not reference the (nonexistent) CastToRecord
      expect(out).not.toContain('CastToRecord');
      // Must not import from node_modules
      expect(out).not.toContain('node_modules');
    } finally {
      cleanup();
    }
  });

  it('checks values against the V type when V is primitive', () => {
    const { run, read, cleanup } = scratch(['RecordCase.ts']);
    try {
      run();
      const out = read('RecordCase.gen.ts');
      // IThing.meta: Record<string, number>
      expect(out).toContain('typeof(obj.meta) === "object"');
      expect(out).toContain('!Array.isArray(obj.meta)');
      expect(out).toContain('Object.values(obj.meta)');
      expect(out).toContain('typeof v === "number"');
    } finally {
      cleanup();
    }
  });

  it('delegates to a named cast function when V is a user interface', () => {
    const { run, read, cleanup } = scratch(['RecordCase.ts']);
    try {
      run();
      const out = read('RecordCase.gen.ts');
      // IRegistry.byId: Record<string, IInner>
      expect(out).toContain('Object.values(obj.byId)');
      expect(out).toContain('CastToInner(v) !== null');
    } finally {
      cleanup();
    }
  });

  it('checks keys against a string-literal union when K is constrained', () => {
    const { run, read, cleanup } = scratch(['RecordCase.ts']);
    try {
      run();
      const out = read('RecordCase.gen.ts');
      // IKeyedFlags.flags: Record<'a' | 'b' | 'c', boolean>
      expect(out).toContain('Object.keys(obj.flags)');
      expect(out).toContain('k === "a"');
      expect(out).toContain('k === "b"');
      expect(out).toContain('k === "c"');
      expect(out).toContain('typeof v === "boolean"');
    } finally {
      cleanup();
    }
  });

  it('handles Record inside a type alias', () => {
    const { run, read, cleanup } = scratch(['RecordCase.ts']);
    try {
      run();
      const out = read('RecordCase.gen.ts');
      // Bag.byKey: Record<string, string>
      expect(out).toContain('Object.values(obj.byKey)');
      expect(out).toContain('typeof v === "string"');
    } finally {
      cleanup();
    }
  });

  it('omits key-param type annotation in JS output', () => {
    const { run, read, cleanup } = scratch(['RecordCase.ts'], { outputLanguage: 'js' });
    try {
      run();
      const out = read('RecordCase.gen.js');
      expect(out).not.toContain('(k: string)');
      expect(out).not.toContain('(v: unknown)');
    } finally {
      cleanup();
    }
  });
});

describe('generateCodegen - node_modules type references', () => {
  it('uses instanceof for runtime-global constructors (Date) by default', () => {
    const { run, read, exists, cleanup } = scratch(['NodeModulesTypes.ts']);
    try {
      run();
      const out = read('NodeModulesTypes.gen.ts');
      // Must not reference a generated CastToDate or import from a node_modules path
      expect(out).not.toContain('CastToDate');
      expect(out).not.toMatch(/from ['"][^'"]*node_modules/);
      // Date is a global constructor — emit instanceof inline
      expect(out).toContain('obj.occurredAt instanceof Date');
      // The redundant existence-check fallback should no longer be emitted
      expect(out).not.toContain('typeof(obj.occurredAt) !== "undefined"');
      // The opt-in side-file must NOT exist
      expect(exists('gencast.nodemodules.gen.ts')).toBe(false);
    } finally {
      cleanup();
    }
  });

  it('emits instanceof for the full set of supported global constructors', () => {
    const { run, read, cleanup } = scratch(['NodeModulesTypes.ts']);
    try {
      run();
      const out = read('NodeModulesTypes.gen.ts');
      expect(out).toContain('obj.when instanceof Date');
      expect(out).toContain('obj.pattern instanceof RegExp');
      expect(out).toContain('obj.pending instanceof Promise');
      expect(out).toContain('obj.cause instanceof Error');
      expect(out).toContain('obj.bag instanceof Map');
      expect(out).toContain('obj.bytes instanceof Uint8Array');
      // Arrays of built-ins use .every(item => item instanceof X)
      expect(out).toContain('obj.many.every');
      expect(out).toContain('item instanceof Date');
    } finally {
      cleanup();
    }
  });

  it('skips non-constructor node_modules types and documents them in a leading comment', () => {
    const { run, read, cleanup } = scratch(['NodeModulesTypes.ts']);
    try {
      run();
      const out = read('NodeModulesTypes.gen.ts');
      // PropertyDescriptor has no runtime constructor — skip with comment, no instanceof
      expect(out).not.toContain('instanceof PropertyDescriptor');
      expect(out).not.toContain('typeof(obj.meta) !== "undefined"');
      expect(out).toContain('Validation skipped');
      expect(out).toContain('meta: PropertyDescriptor');
    } finally {
      cleanup();
    }
  });

  it('writes the shared node_modules gen file when generateNodeModulesCasts is true', () => {
    const { dir, run, read, exists, cleanup } = scratch(['NodeModulesTypes.ts']);
    try {
      // The shared file is resolved relative to process.cwd(), so write it next to the fixture.
      const cwd = process.cwd();
      try {
        process.chdir(dir);
        run({
          generateNodeModulesCasts: true,
          nodeModulesCastsFilePath: './gencast.nodemodules.gen.[ext]',
        });
      } finally {
        process.chdir(cwd);
      }

      // Side file exists with a CastToDate function
      expect(exists('gencast.nodemodules.gen.ts')).toBe(true);
      const sideFile = fs.readFileSync(path.join(dir, 'gencast.nodemodules.gen.ts'), 'utf8');
      expect(sideFile).toContain('export function CastToDate');

      // Caller imports from the side file rather than from node_modules
      const out = read('NodeModulesTypes.gen.ts');
      expect(out).toContain('CastToDate(obj.occurredAt) !== null');
      expect(out).toContain("from './gencast.nodemodules.gen'");
      expect(out).not.toContain('node_modules');
    } finally {
      cleanup();
    }
  });
});

// ---------------------------------------------------------------------------
// exclude
// ---------------------------------------------------------------------------

describe('generateCodegen - exclude', () => {
  it('skips files whose path contains a string entry', () => {
    const { run, exists, cleanup } = scratch(['Gun.ts', 'Types.ts']);
    try {
      run({ exclude: ['Gun.ts'] });
      expect(exists('Gun.gen.ts')).toBe(false);
      expect(exists('Types.gen.ts')).toBe(true);
    } finally {
      cleanup();
    }
  });

  it('skips files whose path matches a RegExp entry', () => {
    const { run, exists, cleanup } = scratch(['Gun.ts', 'Types.ts']);
    try {
      run({ exclude: [/Types\.ts$/] });
      expect(exists('Gun.gen.ts')).toBe(true);
      expect(exists('Types.gen.ts')).toBe(false);
    } finally {
      cleanup();
    }
  });

  it('accepts a single string (not wrapped in an array)', () => {
    const { run, exists, cleanup } = scratch(['Gun.ts', 'Types.ts']);
    try {
      run({ exclude: 'Gun.ts' });
      expect(exists('Gun.gen.ts')).toBe(false);
      expect(exists('Types.gen.ts')).toBe(true);
    } finally {
      cleanup();
    }
  });

  it('accepts a single RegExp (not wrapped in an array)', () => {
    const { run, exists, cleanup } = scratch(['Gun.ts', 'Types.ts']);
    try {
      run({ exclude: /Gun/ });
      expect(exists('Gun.gen.ts')).toBe(false);
      expect(exists('Types.gen.ts')).toBe(true);
    } finally {
      cleanup();
    }
  });

  it('mixes string and RegExp entries', () => {
    const { run, exists, cleanup } = scratch(['Gun.ts', 'Types.ts', 'User.ts']);
    try {
      run({ exclude: ['Gun.ts', /User\.ts$/] });
      expect(exists('Gun.gen.ts')).toBe(false);
      expect(exists('User.gen.ts')).toBe(false);
      expect(exists('Types.gen.ts')).toBe(true);
    } finally {
      cleanup();
    }
  });

  it('matches subdirectory paths using forward slashes (works on Windows too)', () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'gencast-test-'));
    const engineDir = path.join(root, 'src', 'engine');
    const gameDir = path.join(root, 'src', 'game');
    fs.mkdirSync(engineDir, { recursive: true });
    fs.mkdirSync(gameDir, { recursive: true });
    try {
      fs.copyFileSync(path.join(FIXTURES_DIR, 'Gun.ts'), path.join(engineDir, 'Gun.ts'));
      fs.copyFileSync(path.join(FIXTURES_DIR, 'Types.ts'), path.join(gameDir, 'Types.ts'));
      const tsconfigPath = path.join(root, 'tsconfig.json');
      fs.writeFileSync(
        tsconfigPath,
        JSON.stringify({ compilerOptions: { strict: true }, include: ['**/*.ts'] })
      );

      generateCodegen({ tsconfigPath, exclude: ['src/engine'] });

      expect(fs.existsSync(path.join(engineDir, 'Gun.gen.ts'))).toBe(false);
      expect(fs.existsSync(path.join(gameDir, 'Types.gen.ts'))).toBe(true);
    } finally {
      fs.rmSync(root, { recursive: true, force: true });
    }
  });

  it('an empty exclude list processes every file', () => {
    const { run, exists, cleanup } = scratch(['Gun.ts', 'Types.ts']);
    try {
      run({ exclude: [] });
      expect(exists('Gun.gen.ts')).toBe(true);
      expect(exists('Types.gen.ts')).toBe(true);
    } finally {
      cleanup();
    }
  });
});

describe('generateCodegenForPath - exclude', () => {
  it('skips excluded files even when they fall inside a targeted directory', () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'gencast-test-'));
    const subdir = path.join(root, 'models');
    fs.mkdirSync(subdir);
    try {
      fs.copyFileSync(path.join(FIXTURES_DIR, 'Gun.ts'), path.join(subdir, 'Gun.ts'));
      fs.copyFileSync(path.join(FIXTURES_DIR, 'Types.ts'), path.join(subdir, 'Types.ts'));
      const tsconfigPath = path.join(root, 'tsconfig.json');
      fs.writeFileSync(
        tsconfigPath,
        JSON.stringify({ compilerOptions: { strict: true }, include: ['**/*.ts'] })
      );

      generateCodegenForPath(subdir, { tsconfigPath, exclude: [/Gun\.ts$/] });

      expect(fs.existsSync(path.join(subdir, 'Gun.gen.ts'))).toBe(false);
      expect(fs.existsSync(path.join(subdir, 'Types.gen.ts'))).toBe(true);
    } finally {
      fs.rmSync(root, { recursive: true, force: true });
    }
  });
});
