// This is an autogenerated file, DO NOT EDIT.
// This file was generated from `Types.ts` by executing GenCast.
import type { Point, Calculator, Point3D, User, Result, ID, Username, IsActive, Status } from './Types';

  export function CastToPoint(obj: any): Point | null {
    return (obj !== null && obj !== undefined && typeof(obj.x) === "number" && typeof(obj.y) === "number") ? obj : null;
  }
  
  export function CastToCalculator(obj: any): Calculator | null {
    return (obj !== null && obj !== undefined && typeof(obj.add) === "function" && typeof(obj.multiply) === "function") ? obj : null;
  }
  
  export function CastToPoint3D(obj: any): Point3D | null {
    return (obj !== null && obj !== undefined && typeof(obj.x) === "number" && typeof(obj.y) === "number" && typeof(obj.z) === "number") ? obj : null;
  }
  
  export function CastToUser(obj: any): User | null {
    return (obj !== null && obj !== undefined && typeof(obj.id) === "number" && typeof(obj.name) === "string" && (obj.status === "active" || obj.status === "inactive" || obj.status === "pending") && typeof(obj.location) !== "undefined") ? obj : null;
  }
  
  export function CastToResult(obj: any): Result | null {
    return (obj !== null && obj !== undefined && typeof(obj.success) === "boolean") ? obj : null;
  }
  
  export function CastToID(obj: any): ID | null {
    return (typeof(obj) === "number") ? obj : null;
  }
  
  export function CastToUsername(obj: any): Username | null {
    return (typeof(obj) === "string") ? obj : null;
  }
  
  export function CastToIsActive(obj: any): IsActive | null {
    return (typeof(obj) === "boolean") ? obj : null;
  }
  
  export function CastToStatus(obj: any): Status | null {
    return (obj === "active" || obj === "inactive" || obj === "pending") ? obj : null;
  }
  