/**
 * GenCast - Runtime type casting for TypeScript interfaces
 *
 * This module generates type-safe runtime casting functions based on your TypeScript interfaces.
 * It uses duck typing to validate objects at runtime.
 */

import fs from 'fs';
import path from 'path';
import {
  InterfaceDeclaration,
  Project,
  PropertySignature,
  SourceFile,
  Type,
  TypeLiteralNode,
  ts,
} from 'ts-morph';

/**
 * Configuration options for GenCast code generation
 */
export interface GenCastConfig {
  /**
   * The path to the tsconfig.json file for this project.
   * Defaults to './tsconfig.json' in the current working directory.
   */
  tsconfigPath?: string;

  /**
   * The extension for generated files.
   * For instance, if the extension is `.gen.ts`, then the generated file for
   * `MyInterface.ts` will be `MyInterface.gen.ts`.
   * @default '.gen.ts'
   */
  genFileExt?: string;

  /**
   * The prefix for all generated functions.
   * For instance, if the prefix is `CastTo`, then the generated function for
   * `ISomeInterface` will be `CastToSomeInterface`.
   * @default 'CastTo'
   */
  funcPrefix?: string;

  /**
   * If `true`, will try to inline cast functions for interfaces which extend other interfaces.
   * I.e., if `IChild extends IParent`, then the cast function for `IChild` will simply call the
   * cast function for `IParent` instead of checking each property again.
   *
   * If `false`, the cast functions are "inlined" and checks each individual property.
   *
   * Enabling this function can create circular dependencies in your code, depending on your setup.
   * @default false
   */
  preferReuseCastFunctions?: boolean;

  /**
   * Must interfaces be prefixed with an `I`?
   *
   * This is primarily useful for having some control over what interfaces are generated.
   * DOM element interfaces, for instance, do _NOT_ have the I-prefix but you often don't want
   * to generate those.
   * @default false
   */
  requireIPrefix?: boolean;

  /**
   * Controls whether or not an interface without any fields/properties can still be casted to.
   * For example: `type IEmpty = { };`
   *
   * `true` will generate all cast functions for all interfaces, even if they have no properties.
   * `false` will skip interfaces with no properties, and the casting functions will not be generated.
   * @default true
   */
  outputEmptyInterfaces?: boolean;
}

// Simple object containing a bunch of util functions.
const Utils = {
  nullRegex: /\s*\|\s*null\s*|\s*null\s*\|\s*/gi,
  checkTypeNullable: (type: Type<ts.Type>, prop: PropertySignature) =>
    type.isNull() ||
    type.isNullable() ||
    Utils.nullRegex.test(prop.getTypeNodeOrThrow().getText()),

  // Returns the header prefixed to every file that is created by this script
  getGenfileHeader(file: SourceFile) {
    return `// This is an autogenerated file, DO NOT EDIT.
// This file was generated from \`${file.getBaseName()}\` by executing GenCast.\n`;
  },
};

// Default configuration
const DEFAULT_CONFIG: Required<GenCastConfig> = {
  tsconfigPath: './tsconfig.json',
  genFileExt: '.gen.ts',
  funcPrefix: 'CastTo',
  preferReuseCastFunctions: false,
  requireIPrefix: false,
  outputEmptyInterfaces: true,
};

/**
 * Main entry point for GenCast code generation
 * @param userConfig Optional configuration to override defaults
 */
export function generateCodegen(userConfig: GenCastConfig = {}): void {
  const config: Required<GenCastConfig> = {
    ...DEFAULT_CONFIG,
    ...userConfig,
  };

  // Resolve the tsconfig path
  const tsconfigPath = path.resolve(process.cwd(), config.tsconfigPath);

  console.log('GenCast - Generating runtime type casters...');
  console.log(`Using tsconfig: ${tsconfigPath}\n`);

  // Load the source files listed in the tsconfig
  const project = new Project();
  project.addSourceFilesFromTsConfig(tsconfigPath);

  // Process each file and output the relevant file
  project.getSourceFiles().forEach((file) => generateCodegenFile(file, config));

  console.log('\nDone generating interface casters\n');
}

function generateCodegenFile(sourceFile: SourceFile, config: Required<GenCastConfig>) {
  // If this function is called on a previously-generated file, ignore it
  if (sourceFile.getBaseName().endsWith(config.genFileExt)) {
    return;
  }

  const outputFilePath = path.resolve(
    sourceFile.getDirectoryPath(),
    `./${sourceFile.getBaseNameWithoutExtension()}${config.genFileExt}`
  );

  // If this file exists already, just straight up remove it.
  // It may be outdated and no longer necessary, so this will prune the file.
  // If it IS needed, then it'll simply be regenerated.
  if (fs.existsSync(outputFilePath)) {
    fs.unlinkSync(outputFilePath);
  }

  const interfaces = sourceFile.getInterfaces().filter(
    (x) =>
      // Ignore non-exported interfaces as they will cause import errors for the generated files
      x.isExported() &&
      // We might only be looking at the `I`-prefixed interfaces
      (config.requireIPrefix ? x.getName().charAt(0) === 'I' : true)
  );

  // If there are no interfaces in this file at all, then we don't need to look at it further
  if (interfaces.length == 0) {
    return;
  }
  console.log(sourceFile.getBaseName());

  let imports = new Map<SourceFile, Set<string>>();
  let generatedCode = '';
  let hasOutput = false;

  // for each interface found in this source file...
  interfaces.forEach((int) => {
    const interfaceName = int.getName();

    var compiledPropChecks = processInterface(int, imports, config);

    if (compiledPropChecks.length === 0) {
      const color = config.outputEmptyInterfaces ? '🟨' : '❌';
      console.warn(
        `\t${color} No prop checks found for interface "${interfaceName}"`
      );
      if (!config.outputEmptyInterfaces) {
        return;
      }
    }
    hasOutput = true;

    // We may have a type parameter, i.e. this may be a generic function.
    // This snippet will create the necessary `<T, U, ...>` string that's appended to the function
    // as well as the return type.

    let shortGenerics: string[] = [];
    let fullGenerics: string[] = [];

    int.getTypeParameters().forEach((v) => {
      const extension = v.getConstraint()?.getText() || '';
      const longName = v.getName() + (extension ? ` extends ${extension}` : '');
      const shortName = v.getName();

      shortGenerics.push(shortName);
      fullGenerics.push(longName);
    });

    const shortGenString =
      shortGenerics.length > 0 ? `<${shortGenerics.join(', ')}>` : '';
    const fullGenString =
      fullGenerics.length > 0 ? `<${fullGenerics.join(', ')}>` : '';

    // Since the cast functions accept 'any' as a param, we need to double check the possibility
    // that the input is null/undefined
    compiledPropChecks.unshift('obj !== null && obj !== undefined');

    const funcName = `${config.funcPrefix}${removeIPrefixMaybe(interfaceName)}`;
    const checks = compiledPropChecks.join(' && ');

    generatedCode += `
  export function ${funcName}${fullGenString}(obj: any): ${interfaceName}${shortGenString} | null {
    return (${checks}) ? obj : null;
  }
  `;
  });

  if (!hasOutput) {
    return;
  }

  let importString = '';
  const items = imports.entries();

  let value: [SourceFile, Set<string>];
  while ((value = items.next()?.value!)) {
    const [file, members] = value;
    const relativePath = file.getRelativePathAsModuleSpecifierTo(sourceFile);
    importString += `import type { ${Array.from(members.values()).join(
      ', '
    )} } from '${relativePath}';\n`;
  }

  generatedCode =
    Utils.getGenfileHeader(sourceFile) + importString + generatedCode;

  fs.writeFileSync(outputFilePath, generatedCode);
}

function removeIPrefixMaybe(val: string) {
  return val.charAt(0) === 'I' ? val.slice(1) : val;
}

function processInterface(
  interfaceDeclaration: InterfaceDeclaration,
  importsRef: Map<SourceFile, Set<string>>,
  config: Required<GenCastConfig>,
  isInherited: boolean = false
): string[] {
  const propertiesCheckCode: string[] = [];

  const interfaceName = interfaceDeclaration.getName();
  if (config.requireIPrefix && interfaceName.charAt(0) !== 'I') {
    return propertiesCheckCode;
  }

  if (!isInherited) {
    // If this is NOT inherited, then we need to add it to the imports list which is included in
    // the header of the generated file.
    const file = interfaceDeclaration.getSourceFile();
    const list = importsRef.get(file) ?? new Set<string>();
    list.add(interfaceName);
    importsRef.set(file, list);
  }

  // For interfaces with extensions, we will simply confirm that we can cast to the ancestors

  // IF TRYING TO REUSE EXISTING CAST FUNCTIONS...
  if (config.preferReuseCastFunctions) {
    interfaceDeclaration.getBaseDeclarations().forEach((i) => {
      propertiesCheckCode.push(
        `${config.funcPrefix}${removeIPrefixMaybe(i.getName()!)}(obj) !== null`
      );
    });
  } else {
    interfaceDeclaration.getBaseDeclarations().forEach((i) => {
      if (config.requireIPrefix && interfaceName.charAt(0) !== 'I') {
        return propertiesCheckCode;
      }

      if (i.isKind(ts.SyntaxKind.TypeLiteral)) {
        const subProps = processTypeLiteral(<TypeLiteralNode>i);
        propertiesCheckCode.push(...subProps);
      } else {
        const subProps = processInterface(
          <InterfaceDeclaration>i,
          importsRef,
          config,
          true
        );
        propertiesCheckCode.push(...subProps);
      }
    });
  }

  // Ensure all methods exist. (Unfortunately we can't check if the return types are compatible!)
  interfaceDeclaration.getMethods().forEach((meth) => {
    const propName = meth.getName();
    propertiesCheckCode.push(`typeof(obj.${propName}) === "function"`);
  });

  // Check the fields for the given interface, confirming the types are correct
  interfaceDeclaration.getProperties().forEach((prop) => {
    const type: Type<ts.Type> = prop.getType();
    if (
      prop.hasQuestionToken() ||
      type.isAny() ||
      type.getTypeArguments().length > 0
    ) {
      return;
    }

    const isNullable = Utils.checkTypeNullable(type, prop);
    const isStringLiteral = type.isStringLiteral();
    const isStringUnion = type.isUnion() && type.getUnionTypes().every(t => t.isStringLiteral());

    const propName = prop.getName();
    if (type.isAnonymous()) {
      // Actually a method but is showing up as a property! Again, can't check the return type.
      propertiesCheckCode.push(`typeof(obj.${propName}) === "function"`);
    } else if (isNullable) {
      propertiesCheckCode.push(
        `(typeof(obj.${propName}) === "${type.getText()}" || obj.${propName} === null)`
      );
    } else if (type.isTypeParameter()) {
      propertiesCheckCode.push(`typeof(obj.${propName}) !== "undefined"`);
    } else if (isStringLiteral) {
      // Single string literal like "admin"
      propertiesCheckCode.push(`obj.${propName} === ${type.getText()}`);
    } else if (isStringUnion) {
      // Union of string literals like "admin" | "user"
      const checks = type.getUnionTypes()
        .map(t => `obj.${propName} === ${(t as Type<ts.Type>).getText()}`)
        .join(' || ');
      propertiesCheckCode.push(`(${checks})`);
    } else {
      propertiesCheckCode.push(
        `typeof(obj.${propName}) === "${(type as Type<ts.Type>).getText()}"`
      );
    }
  });

  if (!isInherited) {
    console.log(`\t✅ ${interfaceName}`);
  }

  return propertiesCheckCode;
}

function processTypeLiteral(interfaceDeclaration: TypeLiteralNode): string[] {
  const propertiesCheckCode: string[] = [];

  // Check the fields for the given interface, confirming the types are correct
  interfaceDeclaration.getProperties().forEach((prop) => {
    const type: Type<ts.Type> = prop.getType();
    if (
      prop.hasQuestionToken() ||
      type.isAny() ||
      type.getTypeArguments().length > 0
    ) {
      return;
    }

    const isNullable = Utils.checkTypeNullable(type, prop);
    const propName = prop.getName();
    if (type.isAnonymous()) {
      // Actually a method but is showing up as a property! Again, can't check the return type.
      propertiesCheckCode.push(`typeof(obj.${propName}) === "function"`);
    } else if (isNullable) {
      propertiesCheckCode.push(
        `(typeof(obj.${propName}) === "${type.getText()}" || obj.${propName} === null)`
      );
    } else if (type.isTypeParameter()) {
      propertiesCheckCode.push(`typeof(obj.${propName}) !== "undefined"`);
    } else {
      propertiesCheckCode.push(
        `typeof(obj.${propName}) === "${(type as Type<ts.Type>).getText()}"`
      );
    }
  });

  return propertiesCheckCode;
}
