// This is an autogenerated file, DO NOT EDIT.
// This file was generated from `codegen.ts` by executing GenCast.
import type { GenCastConfig } from './codegen';

  export function CastToGenCastConfig(obj: any): GenCastConfig | null {
    return (obj !== null && obj !== undefined) ? obj : null;
  }
  