// This is an autogenerated file, DO NOT EDIT.
// This file was generated from `MyTestFile.ts` by executing the `codegen.ts` file.
import type { IShape } from '../src/MyTestFile';

export function CastToShape(obj: any): IShape | null {
  return (obj !== null && obj !== undefined && typeof(obj.getArea) === "function" && typeof(obj.getName) === "function") ? obj : null;
}
